sudo: false
dist: bionic

language: scala

# so travis finds the tags
install:
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --unshallow --tags

scala:
  - "2.11.12"
  - "2.12.8"
  - "2.13.0"

jdk:
  - openjdk11

node_js:
  - "6"

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
  # GraalVM
    - env: JDK='GraalVM 20'
      install: . ./install-jdk.sh --url "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java8-linux-amd64-20.0.0.tar.gz"

cache:
  directories:
  - "$HOME/.sbt"
  - "$HOME/.cache/coursier"

after_success:
  - '[[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_JDK_VERSION == "openjdk11" ]] && [[ $SONATYPE_USERNAME != "" ]] && { sbt  ++$TRAVIS_SCALA_VERSION publish; };'

env:
  global:
  - secure: DW4OXvjLG04G/k4dPSvOoHOEZ081GLBXP45RbOqGTuC1Kkvi1mOZeOEgPWMfLhimwUxkn3p+6EoddXweXvrcbx7GxR0yazSGGMw8OEeHITPE9c9sfvxXcJkufL+JG+mWiNB5qofaYTogM6QxTlrpIiKY1qHOz/u+gqakGKp4GBM=
  - secure: uWZPYz7Q02Vw7y1pHRKUiJ5oe20m1LJc7UIDQEEEjCxQ92pwlAwoCYWBzr0eaP7bmCJNpvLxIZWa6jPeYZ++HM++nQHewsHpqgVyw1WQ33jQZTlENe3raoPdFpyPrDPE7C2JMIp6QH5g+9zD3m4mdTvKcfTFdYLgKFZNhCWIAV8=
