name: CI - jdk 11 scala 2.12.8

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run tests
      run: sbt ++2.12.8 test
